// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_hGiX2PPN8s0qOGeFOTujRO3wRIKQcc',
    appId: '1:619390270317:web:9884546d0e6b68c7537864',
    messagingSenderId: '619390270317',
    projectId: 'moneyger-daf2f',
    authDomain: 'moneyger-daf2f.firebaseapp.com',
    storageBucket: 'moneyger-daf2f.appspot.com',
    measurementId: 'G-J6BHGV3W60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55eqmL6Ls76wpHKKct4rI5LT5WNCXWBA',
    appId: '1:619390270317:android:a027dd7e616e4571537864',
    messagingSenderId: '619390270317',
    projectId: 'moneyger-daf2f',
    storageBucket: 'moneyger-daf2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzWPHTx3bK3gCTX0MN29dyGfgX2IeLMg',
    appId: '1:619390270317:ios:9e490f77d6654fbb537864',
    messagingSenderId: '619390270317',
    projectId: 'moneyger-daf2f',
    storageBucket: 'moneyger-daf2f.appspot.com',
    iosClientId: '619390270317-av98ahfmfln7hj6m1q799rd7np572cv5.apps.googleusercontent.com',
    iosBundleId: 'com.moneyger.moneyger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzWPHTx3bK3gCTX0MN29dyGfgX2IeLMg',
    appId: '1:619390270317:ios:9e490f77d6654fbb537864',
    messagingSenderId: '619390270317',
    projectId: 'moneyger-daf2f',
    storageBucket: 'moneyger-daf2f.appspot.com',
    iosClientId: '619390270317-av98ahfmfln7hj6m1q799rd7np572cv5.apps.googleusercontent.com',
    iosBundleId: 'com.moneyger.moneyger',
  );
}
